# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.3.9
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: false
odoo_oci_image: docker.jguenat.ch/rumont
odoo_proxy: other
odoo_version: 18.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "16"
project_author: jguenat
project_license: AGPL-3.0-or-later
project_name: rumont-odoo
smtp_default_from: ""
smtp_relay_host: ""
